# Generated by Django 4.0.3 on 2022-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
