# Generated by Django 4.0.3 on 2022-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0002_remove_userregistration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='mobile_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
