# Generated by Django 4.0.3 on 2022-09-09 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0005_alter_userregistration_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 9, 10, 1, 33, 32, 35573)),
        ),
    ]
