# Generated by Django 4.0.3 on 2022-09-09 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0006_userregistration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 1, 35, 42, 839752)),
        ),
    ]
