# Generated by Django 4.0.3 on 2022-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0007_alter_userregistration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
