# Generated by Django 4.0.3 on 2022-09-09 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0008_alter_userregistration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2022, 9, 10, 2, 11, 6, 646773), max_length=122),
        ),
    ]
