# Generated by Django 4.0.6 on 2022-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDZapk', '0009_alter_userregistration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
